Fix: Set ::add-mask:: before processing the vars
lfit/releng-reusable-workflows pull request #81
Opened 2023-11-27 23:37 UTC by askb

2023-11-27 23:54 UTC, askb commented on .github/workflows/compose-packer-verify.yaml
>            echo "::add-mask::${clouds_yaml_b64}" | base64 --decode > "$HOME/.config/openstack/clouds.yaml"
@MightyNerdEric `::add-mask::` does not actually mask the required sensitive info in the previous line and also causes base64 decoding to fail with "Error: bad input". The recommended approach would be to first mask the sensitive data before encoding / decoding .

2023-11-27 23:59 UTC, MightyNerdEric requested changes

2023-11-27 23:59 UTC, MightyNerdEric commented on .github/workflows/compose-packer-verify.yaml
> +          echo "${{ env.CLOUDS_ENV_B64 }}" | sed 's/^ */::add-mask::/'
Could you explain how this is adding the mask? You pipe the echoed string into sed, but you don't seem to be capturing the sed output anywhere. Should this be assigned to the `clouds_env_b64` var?

2023-11-28 02:11 UTC, MightyNerdEric approved these changes

2023-11-28 02:11 UTC, MightyNerdEric commented on .github/workflows/compose-packer-verify.yaml
> +          echo "${{ env.CLOUDS_ENV_B64 }}" | sed 's/^ */::add-mask::/'
Based on our Slack conversation, I now understand that the intention is to print these lines to stdout such that the runner will pick them up as a workflow command. LGTM!

2023-11-28 02:18 UTC, merged